export const RMQ_SERVICES = {
  IAM: 'IAM_SERVICE',
  CATALOG: 'CATALOG_SERVICE',
  DINEIN: 'DINEIN_SERVICE',
  ORDERING: 'ORDERING_SERVICE',
  PAYMENT: 'PAYMENT_SERVICE',
  NOTIFICATION: 'NOTIFICATION_SERVICE',
  REVIEW: 'REVIEW_SERVICE',
  MEDIA: 'MEDIA_SERVICE',
};
